### PR TITLE
fix: egg-etag支持ts

### PR DESCRIPTION
**Pull request by AntiMoron**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

### CODE REVIEW

**Comment by AntiMoron** [comment]
@fengmk2 @atian25 @popomore @huacnlee

**Review by huacnlee — APPROVED** [review]

**Comment by huacnlee** [comment]
https://www.npmjs.com/package/egg-etag

Just released v1.2.0

**Comment by AntiMoron** [comment]
@huacnlee Much thanks!

**Comment by fengmk2** [comment]
@AntiMoron @huacnlee ☆(￣▽￣)/$:*👍🏻

**Pull request merged**
